build-base:
	docker build --target=base -t leaguedex-client:dev .

build-builder:
	docker build --target=builder .

build-production:
	docker build --target=production -t leaguedex-client:production .