name: CI/CD

on:
  push:
    branches: [feature/dockerize-app]
  release:
    types:
      - created

# Trigger on master for staging
# Trigger on release for production
# Determine docker image tag
  # staging -> commit sha
  # production -> release tag
# build images
# push images (dockerhub)
# deploy to correct droplet

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set ENV
      run: |-
        echo ${GITHUB_REF##*/}
        echo ${GITHUB_SHA}

        if [ ${GITHUB_REF##*/} = "dockerize-app" ]; then
          echo 1st condition match
          echo "ENV=staging" >> $GITHUB_ENV
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "DOCKER_DEPLOY_HOST=ssh://user@${{ secrets.STAGING_DROPLET_IP }}" >> $GITHUB_ENV
        else 
          # TODO: Test after merging to master
          echo 2nd condition match
          echo "ENV=prod" >> $GITHUB_ENV
          echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "DOCKER_DEPLOY_HOST=ssh://user@${{ secrets.PRODUCTION_DROPLET_IP }}" >> $GITHUB_ENV
        fi

    # - name: Build Docker Images
    #   run: make build-images

    # - name: Push Docker Images
    #   run: make push-images
    
    - name: Deploy to Droplet
      run: |
        echo $DOCKER_DEPLOY_HOST
        # DOCKER_HOST=$DOCKER_DEPLOY_HOST make deploy
